spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contas_db
    username: postgres
    password: "@Morango272622"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/contas_db
  user: postgres
  password: "@Morango272622"
  schemas: public
  locations: classpath:db/migration
  debug: true
